# Generated by Django 2.2.3 on 2020-07-27 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LuciferMusic', '0002_auto_20200708_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='album_cover')),
                ('company', models.CharField(max_length=20)),
                ('publish_date', models.DateField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='artist_avatar')),
                ('introduction', models.TextField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio')),
                ('lyric', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuciferMusic.Album')),
                ('artists', models.ManyToManyField(to='LuciferMusic.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='user_avatar'),
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='songlist_cover')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(to='LuciferMusic.Song')),
                ('styles', models.ManyToManyField(to='LuciferMusic.Style')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='styles',
            field=models.ManyToManyField(to='LuciferMusic.Style'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LuciferMusic.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='styles',
            field=models.ManyToManyField(to='LuciferMusic.Style'),
        ),
    ]
