# Generated by Django 2.2.3 on 2020-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuciferMusic', '0004_auto_20200727_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='songlist',
            unique_together={('name', 'creator')},
        ),
    ]
