# Generated by Django 2.2.3 on 2020-09-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LuciferMusic', '0009_comment_praise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replay_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LuciferMusic.Comment'),
        ),
    ]
